services:
  mssql:
    platform: linux/amd64
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: cloud9-mssql
    restart: always
    env_file:
      - .env.docker
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - /srv/cloud9/mssql:/var/opt/mssql
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: cloud9-app
    restart: always
    depends_on:
      - mssql
    env_file:
      - .env.docker
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
    ports:
      - "8080:8080"
    volumes:
      - /srv/cloud9/dpkeys:/var/dpkeys
    networks:
      - app-network

networks:
  app-network:
    driver: bridge